### ISSUE TITLE
Why not just use the right command?

### ISSUE THREAD

**Issue by alegrey91** [echo-devim/simba#1]
I mean, you could use the nice `smbclient` which already provide all you needs to do stuffs.
Some examples:
* `smbclient -L //192.168.1.200/ -U 'user1'%'supersecurepassword'`
* `smbclient //192.168.1.200/'directory1' -t 3 -U 'user1'%'supersecurepassword' -c 'put file.php'`

**Comment by 89luca89** [comment]
You can also simply use Thunar or Nautilus to connect directly to the server and let the system keyring manage the authentication
